name: Roderick Gottgens
favicon: null
layout_spectrum: 0.891604
typography_spectrum: 0.1290051
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4b5a6b'
    - '#a1aab3'
    - '#dadde3'
    - '#858c91'
    - '#1f2316'
  brandStrength: 1
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 1
purpose: []
