title: Roderick Gottgens on theGrid.ai
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.3709677
  lightness: 0.8125
  brandColors:
    - '#4b5a6b'
    - '#a1aab3'
    - '#dadde3'
    - '#858c91'
    - '#1f2316'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Roderick Gottgens
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1290051
layout_spectrum: 0.891604
